SELECT 
    B.AUTHOR_ID,
    C.AUTHOR_NAME,
    B.CATEGORY,
    SUM(A.TOTAL * B.PRICE) AS TOTAL_SALES

FROM (
SELECT BOOK_ID,SUM(SALES) AS TOTAL
FROM BOOK_SALES
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY BOOK_ID) A
JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
JOIN AUTHOR C ON B.AUTHOR_ID = C.AUTHOR_ID
GROUP BY B.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC;