SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(30 * C.DAILY_FEE * (1 - D.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R
    ON C.CAR_ID = R.CAR_ID
    AND R.START_DATE <= '2022-11-30'
    AND R.END_DATE >= '2022-11-01'
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE
    AND D.DURATION_TYPE LIKE '30%'
WHERE C.CAR_TYPE IN ('세단','SUV')
  AND R.CAR_ID IS NULL
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;